spring:
  datasource:
    url: jdbc:mysql://localhost:3307/forum_alura_test?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: admin_forum_test
    password: 12345678

api:security:token:secret: ${JWT_SECRET:12345678}